package io.sealfsm.serialize;

import io.sealfsm.model.State;
import io.sealfsm.model.StateMachine;
import io.sealfsm.model.Transition;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Serializes a {@link StateMachine} to W3C SCXML, the interchange format
 * consumed by model-based testing tools. Composite states are rendered as
 * nested {@code <state>} elements. The {@code initial} attribute is set when an
 * initial state was detected.
 *
 * <p>Unresolved transitions are emitted as XML comments rather than as
 * {@code <transition>} elements without a target: this keeps the document
 * schema-valid for downstream tools while still surfacing, in-place, exactly
 * which edges the analyzer could not resolve.
 *
 * <p>Edges whose source is a <em>pseudo-state</em> rather than a permitted
 * subtype — machine entry ({@link StateMachine#INITIAL_PSEUDO_STATE}), or an
 * undetermined source — belong to no {@code <state>} element and so had no
 * natural home here. They are emitted by {@link #emitPseudoStates}: silently
 * omitting them would have broken the invariant that a recovered edge is always
 * visible in the output, and would have left the document's {@code initial}
 * attribute pointing at an element that does not exist.
 */
public final class ScxmlSerializer {

    private static final String NS = "http://www.w3.org/2005/07/scxml";

    public String serialize(StateMachine m) {
        StringBuilder sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<scxml xmlns=\"").append(NS).append("\" version=\"1.0\"");
        sb.append(" name=\"").append(attr(m.name())).append('"');
        m.initialState().ifPresent(init -> sb.append(" initial=\"").append(attr(scxmlId(init))).append('"'));
        sb.append(">\n");
        sb.append("  <!-- Generated by SealFSM from sealed hierarchy ")
          .append(esc(m.qualifiedName())).append(" -->\n");
        sb.append("  <!-- Encoding style: ").append(m.encoding())
          .append("; states: ").append(m.allStates().size())
          .append("; transitions resolved/total: ")
          .append(m.resolvedTransitionCount()).append('/').append(m.transitions().size())
          .append(" -->\n");

        for (State s : m.topLevelStates()) {
            emitState(m, s, sb, "  ");
        }
        emitPseudoStates(m, sb, "  ");
        sb.append("</scxml>\n");
        return sb.toString();
    }

    /**
     * Emit the edges whose source is not a permitted subtype. There are two kinds
     * and they are treated differently on purpose:
     *
     * <ul>
     *   <li><b>Machine entry</b> is a real entry point — the analyzer proved which
     *       state the machine starts in. It becomes an actual {@code <state>}
     *       element so the document's {@code initial} attribute resolves, which it
     *       otherwise would not.</li>
     *   <li><b>Undetermined source</b> means the analyzer recovered a target but
     *       could not attribute a from-state. That is a gap, not a state, so
     *       inventing a {@code <state>} for it would put a fiction in the model.
     *       These are emitted as comments — the same treatment unresolved targets
     *       already get, and for the same reason.</li>
     * </ul>
     */
    private void emitPseudoStates(StateMachine m, StringBuilder sb, String indent) {
        Set<String> realIds = new HashSet<>();
        for (State s : m.allStates()) realIds.add(s.id());

        List<Transition> entry = new ArrayList<>();
        List<Transition> orphans = new ArrayList<>();
        for (Transition t : m.transitions()) {
            if (realIds.contains(t.from())) continue;
            if (StateMachine.INITIAL_PSEUDO_STATE.equals(t.from())) entry.add(t);
            else orphans.add(t);
        }

        if (!entry.isEmpty()) {
            sb.append(indent)
              .append("<!-- Synthetic entry pseudo-state: the machine's start point, from which the\n")
              .append(indent)
              .append("     analyzer proved these initial transitions. Not a permitted subtype. -->\n");
            sb.append(indent).append("<state id=\"")
              .append(attr(scxmlId(StateMachine.INITIAL_PSEUDO_STATE))).append("\">\n");
            for (Transition t : entry) {
                emitTransition(t, sb, indent + "  ");
            }
            sb.append(indent).append("</state>\n");
        }

        if (!orphans.isEmpty()) {
            sb.append(indent).append("<!-- ").append(orphans.size())
              .append(" transition(s) whose SOURCE state could not be determined; recorded here\n")
              .append(indent)
              .append("     rather than dropped, since they depress recall and must stay visible: -->\n");
            for (Transition t : orphans) {
                sb.append(indent).append("<!-- from ").append(esc(t.from()))
                  .append(t.event() != null ? " on event '" + esc(t.event()) + "'" : "")
                  .append(t.guard() != null ? " when '" + esc(t.guard()) + "'" : "")
                  .append(t.isResolved() ? " -> " + esc(t.to())
                                         : "; target source: " + esc(String.valueOf(t.note())))
                  .append(" -->\n");
            }
        }
    }

    private void emitState(StateMachine m, State s, StringBuilder sb, String indent) {
        boolean composite = s.isComposite() && !s.children().isEmpty();
        sb.append(indent).append("<state id=\"").append(attr(s.id())).append('"');

        // For a composite state, default its initial child to the first one declared.
        if (composite) {
            sb.append(" initial=\"").append(attr(s.children().get(0).id())).append('"');
        }
        sb.append(">\n");

        // Outgoing transitions whose source is this state.
        for (Transition t : m.transitions()) {
            if (!t.from().equals(s.id())) continue;
            emitTransition(t, sb, indent + "  ");
        }

        if (composite) {
            for (State child : s.children()) {
                emitState(m, child, sb, indent + "  ");
            }
        }
        sb.append(indent).append("</state>\n");
    }

    private void emitTransition(Transition t, StringBuilder sb, String indent) {
        if (!t.isResolved()) {
            sb.append(indent).append("<!-- unresolved transition")
              .append(t.event() != null ? " on event '" + esc(t.event()) + "'" : "")
              .append(t.note() != null ? "; target source: " + esc(t.note()) : "")
              .append(" -->\n");
            return;
        }
        // An SCXML transition with no `event` is already the eventless/default one,
        // which is exactly the "otherwise" edge; the comment records that this is
        // deliberate rather than an event the analyzer failed to recover.
        if (t.event() == null && t.isOtherwise()) {
            sb.append(indent).append("<!-- default (otherwise) transition -->\n");
        }
        sb.append(indent).append("<transition");
        if (t.event() != null) sb.append(" event=\"").append(attr(t.event())).append('"');
        if (t.guard() != null) sb.append(" cond=\"").append(attr(t.guard())).append('"');
        sb.append(" target=\"").append(attr(scxmlId(t.to()))).append("\"/>\n");
    }

    /**
     * SCXML state ids are XML names; the analyzer's pseudo-states are spelled
     * {@code <initial>} / {@code <unknown>}, which are not. Strip the brackets and
     * prefix with an underscore so the emitted id is a legal NCName and cannot
     * collide with a real state (a Java simple name never starts with {@code _}
     * here, and real ids pass through untouched).
     */
    private static String scxmlId(String stateId) {
        if (stateId != null && stateId.length() > 2
                && stateId.charAt(0) == '<' && stateId.charAt(stateId.length() - 1) == '>') {
            return "_" + stateId.substring(1, stateId.length() - 1);
        }
        return stateId;
    }

    /** Escape text content for XML. */
    private static String esc(String raw) {
        return raw.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;");
    }

    /** Escape an XML attribute value. */
    private static String attr(String raw) {
        return esc(raw).replace("\"", "&quot;");
    }
}
