package io.sealfsm.serialize;

import io.sealfsm.model.State;
import io.sealfsm.model.StateMachine;
import io.sealfsm.model.Transition;

/**
 * Serializes a {@link StateMachine} to W3C SCXML, the interchange format
 * consumed by model-based testing tools. Composite states are rendered as
 * nested {@code <state>} elements. The {@code initial} attribute is set when an
 * initial state was detected.
 *
 * <p>Unresolved transitions are emitted as XML comments rather than as
 * {@code <transition>} elements without a target: this keeps the document
 * schema-valid for downstream tools while still surfacing, in-place, exactly
 * which edges the analyzer could not resolve.
 */
public final class ScxmlSerializer {

    private static final String NS = "http://www.w3.org/2005/07/scxml";

    public String serialize(StateMachine m) {
        StringBuilder sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<scxml xmlns=\"").append(NS).append("\" version=\"1.0\"");
        sb.append(" name=\"").append(attr(m.name())).append('"');
        m.initialState().ifPresent(init -> sb.append(" initial=\"").append(attr(init)).append('"'));
        sb.append(">\n");
        sb.append("  <!-- Generated by SealFSM from sealed hierarchy ")
          .append(esc(m.qualifiedName())).append(" -->\n");
        sb.append("  <!-- Encoding style: ").append(m.encoding())
          .append("; states: ").append(m.allStates().size())
          .append("; transitions resolved/total: ")
          .append(m.resolvedTransitionCount()).append('/').append(m.transitions().size())
          .append(" -->\n");

        for (State s : m.topLevelStates()) {
            emitState(m, s, sb, "  ");
        }
        sb.append("</scxml>\n");
        return sb.toString();
    }

    private void emitState(StateMachine m, State s, StringBuilder sb, String indent) {
        boolean composite = s.isComposite() && !s.children().isEmpty();
        sb.append(indent).append("<state id=\"").append(attr(s.id())).append('"');

        // For a composite state, default its initial child to the first one declared.
        if (composite) {
            sb.append(" initial=\"").append(attr(s.children().get(0).id())).append('"');
        }
        sb.append(">\n");

        // Outgoing transitions whose source is this state.
        for (Transition t : m.transitions()) {
            if (!t.from().equals(s.id())) continue;
            emitTransition(t, sb, indent + "  ");
        }

        if (composite) {
            for (State child : s.children()) {
                emitState(m, child, sb, indent + "  ");
            }
        }
        sb.append(indent).append("</state>\n");
    }

    private void emitTransition(Transition t, StringBuilder sb, String indent) {
        if (!t.isResolved()) {
            sb.append(indent).append("<!-- unresolved transition")
              .append(t.event() != null ? " on event '" + esc(t.event()) + "'" : "")
              .append(t.note() != null ? "; target source: " + esc(t.note()) : "")
              .append(" -->\n");
            return;
        }
        sb.append(indent).append("<transition");
        if (t.event() != null) sb.append(" event=\"").append(attr(t.event())).append('"');
        if (t.guard() != null) sb.append(" cond=\"").append(attr(t.guard())).append('"');
        sb.append(" target=\"").append(attr(t.to())).append("\"/>\n");
    }

    /** Escape text content for XML. */
    private static String esc(String raw) {
        return raw.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;");
    }

    /** Escape an XML attribute value. */
    private static String attr(String raw) {
        return esc(raw).replace("\"", "&quot;");
    }
}
